version: "3"
services:
  backend:
    container_name: backend
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    command: sh ./misc/scripts/gunicorn_launch.sh
    networks:
      - internal

  frontend:
    container_name: frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.dockerfile

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    networks:
      - internal
    volumes:
      - persistent:/var/lib/postgres/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    links:
      - postgres:postgres
    networks:
      - internal
    depends_on:
      - postgres

    env_file:
      - .env
    ports:
      - "5050:5050"
    logging:
      driver: none

  redis:
    image: redis:6-alpine
    container_name: redis
    env_file:
      - .env
    command: redis-server --requirepass ${SECRET_KEY}
    networks:
      - internal

  file_server:
    container_name: file_server
    build:
      context: ./dockerfiles
      dockerfile: ./file_server.dockerfile
    networks:
      - internal
    volumes:
      - uploads:/usr/share/nginx/html

volumes:
  persistent:
  uploads:

networks:
  internal:
    driver: bridge
