services:
    postgres:
        image: postgres:13-alpine
        container_name: postgres
        networks:
            - internal
        volumes:
            - persistent:/var/lib/postgres/data
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgres/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        links:
            - postgres:postgres
        networks:
            - internal
        depends_on:
            - postgres

        env_file:
            - .env
        ports:
            - "5050:5050"
        logging:
            driver: none

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        logging:
            driver: "none"
        networks:
            - internal
        ports:
            - "8025:8025"

    redis:
        image: redis:6-alpine
        container_name: redis
        env_file:
            - .env
        command: redis-server --requirepass test
        networks:
            - internal

volumes:
    persistent:

networks:
    internal:
        driver: bridge
