version: '3'
services:
    postgres:
        ports:
            - "5432:5432"

    redis:
        ports:
            - "6379:6379"

    backend:
        ports:
          - "8080:80"

    pgadmin:
        environment:
            - PGADMIN_LISTEN_PORT=5050
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}

    file_server:
        volumes:
            - ./file_server:/usr/share/nginx/html

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        networks:
            - internal
        ports:
            - "8025:8025"
            - "1025:1025"

